version: "3.5"
services:
  beacon-chain:
    build:
      context: ./beacon-chain
      args:
        BEACON_API_PORT: 3500
        UPSTREAM_VERSION: 22.6.1
    environment:
      BEACON_API_PORT: 3500
      HTTP_WEB3PROVIDER: "http://geth-ropsten.dappnode:8545"
      HTTPS_ENGINE: "http://geth-ropsten.dappnode:8551"
      TTD_OVERRIDE: 50000000000000000
      CHECKPOINT_SYNC_URL: ""
      EXTRA_OPTS: ""
    volumes:
      - "teku-ropsten-data:/opt/teku/data"
    ports:
      - 9000/tcp
      - 9000/udp
    restart: unless-stopped
    image: "beacon-chain.teku-ropsten.dnp.dappnode.eth:0.1.0"
  validator:
    build:
      context: ./validator
      args:
        UPSTREAM_VERSION: 22.6.1
    environment:
      LOG_TYPE: INFO
      BEACON_NODE_ADDR: "http://beacon-chain.teku-ropsten.dappnode:3500"
      GRAFFITI: validating_from_DAppNode
      EXTRA_OPTS: ""
      FEE_RECIPIENT_ADDRESS: ""
    restart: unless-stopped
    image: "validator.teku-ropsten.dnp.dappnode.eth:0.1.0"
volumes:
  teku-ropsten-data: {}
